@startuml
'https://plantuml.com/class-diagram

class User {
- String username
- String password
+createUser(String username, String password)
+login(String username, String password)
+savedMedia()
+watchedMedia()
}

abstract class Media {
- String title
- String category
- int duration
- int rating
- int releaseYear
}

class Movie extends Media {
}

class HeadMenu {

    +{static}searchMedia(String name)
    +{static}searchMediaByCategory(String name)
    +{static}showSavedMedia()
    +{static}showWatchedMedia()
    +{static}chooseMedia()
    +{static}addMediaToSaved()
    +{static}addMediaToWatched()
}

class FileIO{
}

class App {
    +startApp()
}

class Series extends Media {
    - int seasons
    - int episodes
}

@enduml


